// TRATAMENTO DE ERROS
#define SUCCESS 0
#define ERRO_NO_TIPO_INTEIRO -1
#define ERRO_NO_TAMANHO_STRING -2
#define	ERRO_NOME_CAMPO -3
#define ERRO_NOME_TABELA -4
#define ERRO_DE_PARAMETRO -5
#define ERRO_ABRIR_ARQUIVO -6
#define ERRO_VAZIO -7
#define ERRO_IMPRESSAO -8
#define ERRO_LEITURA_DADOS -9
#define ERRO_BUFFER_CHEIO -10
#define ERRO_ABRIR_DICIONARIO -11
#define ERRO_NO_TIPO_CHAR -12
#define ERRO_NO_TIPO_DOUBLE -13
#define ERRO_CHAVE_PRIMARIA -14
#define ERRO_CHAVE_ESTRANGEIRA -15
#define ERRO_CRIACAO_TABELA -16
#define ERRO_REMOVER_ARQUIVO -17
#define ERRO_REMOVER_ARQUIVO_OBJECT -18
#define ERRO_REMOVER_ARQUIVO_SCHEMA -19
#define ERRO_DE_ALOCACAO NULL
#define ERRO_ABRIR_ESQUEMA NULL
#define ERRO_NOME_TABELA_INVALIDO NULL
#define ERRO_ESTRUTURA_TABELA_NULA NULL
#define ERRO_INSERIR_VALOR NULL
#define ERRO_PAGINA_INVALIDA NULL
#define ERRO_DE_LEITURA NULL
#define ERRO_PARAMETRO NULL

//tratamento PK e FK
#define NPK 0
#define PK 1
#define FK 2

